USE prototype;

CREATE TABLE IF NOT EXISTS users ( 
  id INT AUTO_INCREMENT PRIMARY KEY, 
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  username VARCHAR(30) NOT NULL UNIQUE, 
  email VARCHAR(100) NOT NULL UNIQUE, 
  password_hash VARCHAR(255) NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);